### PR TITLE
about.html page #160

### PR DESCRIPTION
**Pull request by Huma-a**
Replace dummy tweets in footer of about.html page #160

### CODE REVIEW

**Review by bjornmage — CHANGES_REQUESTED** [review]
Line 468 doesn't have the correct spacing from the original. After the word "plays" you need to have a line break (hit enter)

**Review by Huma-a — COMMENTED** [review]
I made suggested changes. thankyou

**Review by Huma-a — COMMENTED** [review]
I made suggested changes.

**Review by Huma-a — COMMENTED** [review]
i have made suggested changes

**Comment by misterhackney** [comment]
@Aleem-Reveltek  - please help with this.

**Review by Huma-a — COMMENTED** [review]
I made a correction.

**Review by Huma-a — COMMENTED** [review]
I made corrections.

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Line 469 does not follow the original character count, refer [5d9b3e3](https://github.com/WorldEnterpriseGroup/alliedcare/pull/161/commits/5d9b3e3fa49c6bc68ecd321463423c19a0e437a7).

**Pull request closed without merging**
