### PR TITLE
updated the dummy tweet #01

### PR DESCRIPTION
**Pull request by Zaryabayub**
Replaced dummy content of "LATEST TWEETS" tweet #01 in footer of services.html page #138

### CODE REVIEW

**Review by Zaryabayub — COMMENTED** [review]
made changes to tweet no 1

**Review by misterhackney — CHANGES_REQUESTED** [review]
This has the following problems:

Does not respect character count
Please do further training so you can get the appropriate character count.

**Comment by misterhackney** [comment]
@UmerManager  - address this

**Comment by Zaryabayub** [comment]
Its already changed my someone. And merged by the organization. I am going to close this pull request.

**Pull request closed without merging**
